
services:
  fastapi-backend:
    image: a00835462/howl_ai:v0.6
    build:
      context: ./app

    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.oci:/root/.oci 
      - ./tests:/app/tests 

    env_file:
      - .env

    restart: unless-stopped
