
services:
  fastapi-backend:
    build:
      context: ./app

    container_name: fastapi-app
    ports:
      - "443:443"
      # - "8000:8000"
    volumes:
      - ./app:/app
      - ./.oci:/root/.oci 

    env_file:
      - .env

    restart: unless-stopped
