
services:
  fastapi-backend:
    image: a00835462/howl_ai:v0.1
    build:
      context: ./app

    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.oci:/root/.oci 

    env_file:
      - .env

    restart: unless-stopped
