
services:
  fastapi-backend:
    image: a00835462/howl_ai:v0.6
    build:
      context: ./app

    container_name: fastapi-app
    ports:
    # uncoment below to use https
      - "443:443"
      # - "8000:8000"
    volumes:
      - ./app:/app
      - ./.oci:/root/.oci 
      - ./tests:/app/tests 
    environment:
      - PYTHONPATH=/app:/app/tests
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
